name: CI
 
on: [push]
 
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 .
      - name: Install pytest
        run: pip install pytest
      - name: Run testing
        run: pytest
      - name: Deploy to GCP VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            echo "Checking for running Flask app..."
            thePID=$(pgrep -f "python3 app.py")
            echo "thePID: $thePID"

            if [[ "$thePID" > "0" ]]; then
              echo "Flask app is running. Stopping it..."
              echo "kill $thePID"
              kill $thePID
              echo "Completed"
            else
              echo "Flask app is not running."
            fi
            
            echo "Changing Directories..."
            cd /home/${{ secrets.GCP_VM_USER }}/Code/Confident-Coders-Modern-Software-Development-Assignment
            
            echo "Getting fresh code..."
            git pull origin main
            
            echo "Installing requirements..."
            pip3 install -r requirements.txt
            
            echo "Running the app..."
            python3 app.py