name: CI
 
on: [push]
 
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 .
      - name: Install pytest
        run: pip install pytest
      - name: Run testing
        run: pytest
      - name: Deploy to GCP VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            echo "Cloning and Dockerizing a fresh copy of the flask app..."
            set -e
            
            echo "Stop the Docker container..."
            sudo docker ps -q | xargs -r sudo docker stop
            sudo docker ps -a -q | xargs -r sudo docker rm
            
            echo "Get the current version on the repo..."
            rm -rf /tmp/tmpRepo
            git clone https://github.com/mamccorkle/Confident-Coders-Modern-Software-Development-Assignment.git /tmp/tmpRepo
            
            echo "Checking for the Dockerfile..."
            if [ ! -f Dockerfile ]; then
              echo "ERROR: Dockerfile not found in $(pwd)"
              exit 1
            fi
            
            echo "Create the new Docker image..."
            cd /tmp/tmpRepo
            sudo docker build -t leaderboard .
            
            echo "Start the Docker container in detached mode..."
            sudo docker run -d --name leaderboard_container -p 80:5000 leaderboard